matrix:

  include:

    - language: php

      sudo: required

      dist: xenial

      php:
        - 7.1
        - 7.2

      addons:
        postgresql: 9.5
        chrome: stable

      env:
        - APP_URL=http://localhost:8000
        - APP_ENV=testing
        - DB_CONNECTION=pgsql
        - DB_HOST=localhost
        - DB_PORT=5432
        - DB_DATABASE=travis
        - DB_USERNAME=postgres
        - DB_PASSWORD=
        - API_ACCESS_KEY=ieducar-access-key
        - API_SECRET_KEY=ieducar-secret-key
        - DISPLAY=:99.0

      cache:
        directories:
          - $HOME/.composer/cache

      before_script:
        - composer new-install
        - vendor/laravel/dusk/bin/chromedriver-linux 2>&1 > /dev/null &
        - php artisan serve 2>&1 > /dev/null &

      script:
        - vendor/bin/phpunit
        - php artisan dusk
