matrix:
  include:
    - language: php
      php:
        - 7.1
        - 7.2
      addons:
        postgresql: 9.5
      env:
        - APP_ENV=testing
        - DB_CONNECTION=pgsql
        - DB_HOST=localhost
        - DB_PORT=5432
        - DB_DATABASE=travis
        - DB_USERNAME=postgres
        - DB_PASSWORD=
        - API_ACCESS_KEY=ieducar-access-key
        - API_SECRET_KEY=ieducar-secret-key

      cache:
        directories:
          - $HOME/.composer/cache
      before_script:
        - composer new-install
