ieducar_1204:
  build: .
  environment:
    - CORE_EXT_CONFIGURATION_ENV=development
  ports:
    - "8001:80"
  volumes:
    - .:/home/portabilis/ieducar
  links:
    - postgres_95
  container_name: ieducar_1204

postgres_95:
  volumes:
    - /var/lib/postgresql/data
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - "5433:5432"